export const SIGNIN_USERS_REQUEST = 'users/SIGNIN/REQUEST';
export const SIGNIN_USERS_SUCCESS = 'users/SIGNIN/SUCCESS';
export const SIGNIN_USERS_FAILURE = 'users/SIGNIN/FAILURE';

export const SIGNUP_USERS_REQUEST = 'users/SIGNUP/REQUEST';
export const SIGNUP_USERS_SUCCESS = 'users/SIGNUP/SUCCESS';
export const SIGNUP_USERS_FAILURE = 'users/SIGNUP/FAILURE';

export const SIGNOUT_USERS = 'users/SIGNOUT';

export const CHECK_SESSION_USERS_REQUEST = 'users/CHECK_SESSION/REQUEST';
export const CHECK_SESSION_USERS_SUCCESS = 'users/CHECK_SESSION/SUCCESS';
export const CHECK_SESSION_USERS_FAILURE = 'users/CHECK_SESSION/FAILURE';
