export const FETCH_ALL_AUTHORS_REQUEST = 'authors/FETCH_ALL/REQUEST';
export const FETCH_ALL_AUTHORS_SUCCESS = 'authors/FETCH_ALL/SUCCESS';

export const FETCH_AUTHOR_REQUEST = 'authors/FETCH_ONE/REQUEST';
export const FETCH_AUTHOR_SUCCESS = 'authors/FETCH_ONE/SUCCESS';
